{% set version = "3.0.1" %}
{% set name = "symmetrica" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://gitlab.com/sagemath/symmetrica/-/archive/{{ version }}/symmetrica-{{ version }}.tar.gz
  sha256: 6e0fea5708d2deed8369ce4c7c2123a23a1c942d8cdf39c1f81258aec3ac04ec

build:
  number: 0
  skip: True    # [win and vc<14]
  run_exports:
    - {{ pin_subpackage("symmetrica", max_pin="x.x") }}

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - clangxx  # [ppc64le]
  host:
  run:

test:
  commands:
    - test -f ${PREFIX}/include/symmetrica/macro.h   # [unix]
    - test -f ${PREFIX}/lib/libsymmetrica${SHLIB_EXT}          # [unix]
    - if not exist %LIBRARY_INC%\\symmetrica\\macro.h exit 1       # [win]
    - if not exist %LIBRARY_LIB%\\symmetrica.lib exit 1           # [win]

about:
  home: http://www.algorithm.uni-bayreuth.de/en/research/SYMMETRICA/index.html
  license: ISC
  license_file: LICENSE
  summary: |
    Symmetrica is a collection of routines to handle several topics including
    ordinary representation theory of the symmetric group and related groups

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
    - alexjbest
